# Site settings
title: Coralie Clot
description: This is an example site for GitHub Pages.
url: "https://coralieclot.github.io"
baseurl: "/coralieclot.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Permalinks
permalink: /:categories/:year/:month/:day/:title/

# Exclusions
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# # Google Analytics
# google_analytics: UA-XXXXXXXX-X

# Social media settings
github_username: coralieclot
linkedin_username: coralieclot

# Markdown settings
kramdown:
  input: GFM
  hard_wrap: false

# Other settings
paginate: 5
paginate_path: "/page:num/"
